// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFQvkN8qzP2G36VaL_zw15khxdig0pCT0',
    appId: '1:177069340202:web:61922beb7391b71dc0f553',
    messagingSenderId: '177069340202',
    projectId: 'my-todolist-project-4948',
    authDomain: 'my-todolist-project-4948.firebaseapp.com',
    storageBucket: 'my-todolist-project-4948.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSEHnCmMisMMp8-5buZDzTwL-jduQG_2w',
    appId: '1:177069340202:android:f097a96433629a7cc0f553',
    messagingSenderId: '177069340202',
    projectId: 'my-todolist-project-4948',
    storageBucket: 'my-todolist-project-4948.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAydDJLaULwsBiKrUXKzuPnXCOA9xc9mnc',
    appId: '1:177069340202:ios:ce7e937c7cdb07d2c0f553',
    messagingSenderId: '177069340202',
    projectId: 'my-todolist-project-4948',
    storageBucket: 'my-todolist-project-4948.appspot.com',
    iosClientId: '177069340202-kluvivoddppmh1d7b6gv0gpft7b3f5c6.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAydDJLaULwsBiKrUXKzuPnXCOA9xc9mnc',
    appId: '1:177069340202:ios:ce7e937c7cdb07d2c0f553',
    messagingSenderId: '177069340202',
    projectId: 'my-todolist-project-4948',
    storageBucket: 'my-todolist-project-4948.appspot.com',
    iosClientId: '177069340202-kluvivoddppmh1d7b6gv0gpft7b3f5c6.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );
}
