import 'package:flutter/material.dart';

Color themeColor = Color.fromARGB(255, 233, 8, 83);
Color textColor = Colors.white;
List<Color> colorsList = [
  Colors.green,
  Colors.red,
  Colors.blue,
  Colors.black,
  Colors.grey,
  Colors.yellow,
  Colors.orange,
  Colors.deepOrange,
  Colors.black,
  Colors.white,
  Colors.amber,
  Colors.amberAccent,
  Colors.blueAccent,
  Colors.blueGrey,
  Colors.brown,
  Colors.cyan,
  Colors.cyanAccent,
  Colors.deepOrangeAccent,
  Colors.deepPurple,
  Colors.deepPurpleAccent,
  Colors.greenAccent,
  Colors.indigo,
  Colors.indigoAccent,
  Colors.lightBlue,
  Colors.lightBlueAccent,
  Colors.lightGreen,
  Colors.lightGreenAccent,
  Colors.lime,
  Colors.limeAccent,
  Colors.orangeAccent,
  Colors.pink,
  Colors.pinkAccent,
  Colors.purple,
  Colors.purpleAccent,
  Colors.redAccent,
  Colors.teal,
  Colors.tealAccent,
  Colors.yellowAccent,
];
