import 'package:flutter/material.dart';

List<String> materials = [
  "Lace",
  "Ankara",
  "Guinea",
  "Linen",
  "Silk",
  "Wool",
  "Cotten"
];
Map<String, Color> colorsMap = {
  "green": Colors.green,
  "red": Colors.red,
  "blue": Colors.blue,
  "black": Colors.black,
  "grey": Colors.grey,
  "yellow": Colors.yellow,
  "orange": Colors.orange,
  "deepOrange": Colors.deepOrange,
  "white": Colors.white,
  "amber": Colors.amber,
  "amberAccent": Colors.amberAccent,
  "blueAccent": Colors.blueAccent,
  "blueGrey": Colors.blueGrey,
  "brown": Colors.brown,
  "cyan": Colors.cyan,
  "cyanAccent": Colors.cyanAccent,
  "deepOrangeAccent": Colors.deepOrangeAccent,
  "deepPurple": Colors.deepPurple,
  "deepPurpleAccent": Colors.deepPurpleAccent,
  "greenAccent": Colors.greenAccent,
  "indigo": Colors.indigo,
  "indigoAccent": Colors.indigoAccent,
  "lightBlue": Colors.lightBlue,
  "lightBlueAccent": Colors.lightBlueAccent,
  "lightGreen": Colors.lightGreen,
  "lightGreenAccent": Colors.lightGreenAccent,
  "lime": Colors.lime,
  "limeAccent": Colors.limeAccent,
  "orangeAccent": Colors.orangeAccent,
  "pink": Colors.pink,
  "pinkAccent": Colors.pinkAccent,
  "purple": Colors.purple,
  "purpleAccent": Colors.purpleAccent,
  "redAccent": Colors.redAccent,
  "teal": Colors.teal,
  "tealAccent": Colors.tealAccent,
  "yellowAccent": Colors.yellowAccent,
};

List<String> bagProductKeys = [
  "breadth",
  "waist",
  "length",
  "color",
  "material",
  "price",
  "qty",
  "productID",
  "productName",
  "productDesigner",
  "productImage"
];
